/** Permanent cover images committed in /public/covers — survive Hostinger redeploys. */
import { POST_COVERS } from "@/lib/postCovers.generated";

const COVERS: Record<string, string> = {
  applications: "/covers/applications.svg",
  careers: "/covers/careers.svg",
  scholarships: "/covers/scholarships.svg",
  skills: "/covers/skills.svg",
  "study-abroad": "/covers/study-abroad.svg",
  technology: "/covers/technology.svg",
  tutorials: "/covers/tutorials.svg",
  lifestyle: "/covers/lifestyle.svg",
};

export const DEFAULT_COVER = "/covers/default.svg";

const OWN_HOSTS = new Set(["globalcareerhub.org", "www.globalcareerhub.org"]);
/** Files from this repo's public/ dir (e.g. raw.githubusercontent links saved by the migrate tool). */
const REPO_RAW = /^https?:\/\/raw\.githubusercontent\.com\/faham112\/nextjs-mysql-blog\/[^/]+\/public(\/.+)$/i;

/**
 * Branded per-post cover generated by scripts/generate-post-covers.mjs and committed to
 * public/covers/posts/<slug>.(webp|png). Returns the WebP path (page display) or null.
 */
export function postCover(slug?: string | null): string | null {
  if (!slug) return null;
  return Object.prototype.hasOwnProperty.call(POST_COVERS, slug) ? `/covers/posts/${slug}.webp` : null;
}

/** Descriptive alt text for a post's cover (falls back to the title). */
export function coverAlt(slug: string | null | undefined, title: string): string {
  if (slug && Object.prototype.hasOwnProperty.call(POST_COVERS, slug)) return POST_COVERS[slug];
  return title;
}

export function coverForCategory(slug?: string | null): string {
  if (!slug) return DEFAULT_COVER;
  return COVERS[slug.toLowerCase()] || DEFAULT_COVER;
}

/** Uploaded files live in public/uploads (gitignored) and are wiped on every deploy. */
function isEphemeralPath(pathname: string): boolean {
  return pathname.startsWith("/uploads/") || pathname.startsWith("/api/media/");
}

/**
 * Resolve the image to show for a post. Always returns a usable URL:
 *  - a branded per-post cover in /covers/posts/<slug> wins when it exists
 *  - /covers/* (git-hosted, survive redeploys) are used as-is
 *  - raw.githubusercontent links to this repo's public/ are served locally
 *  - external https images are used as-is
 *  - /uploads/* and /api/media/* (wiped on every Hostinger deploy) fall back to the
 *    category cover unless USE_UPLOAD_IMAGES=1 (only set once uploads are persistent)
 *  - anything else falls back to the category cover
 */
export function resolveCover(
  featuredImage?: string | null,
  categorySlug?: string | null,
  postSlug?: string | null
): string {
  const own = postCover(postSlug);
  if (own) return own;
  const fallback = coverForCategory(categorySlug);
  const raw = (featuredImage || "").trim();
  if (!raw) return fallback;

  const repoMatch = raw.match(REPO_RAW);
  if (repoMatch) {
    const local = repoMatch[1];
    return local.startsWith("/covers/") ? local : fallback;
  }

  let pathname = raw;
  if (/^https?:\/\//i.test(raw)) {
    let u: URL;
    try {
      u = new URL(raw);
    } catch {
      return fallback;
    }
    if (!OWN_HOSTS.has(u.hostname.toLowerCase())) {
      // External CDN image
      return u.protocol === "https:" ? raw : fallback;
    }
    pathname = u.pathname;
  } else if (!raw.startsWith("/") || raw.startsWith("//")) {
    return fallback;
  }

  if (pathname.startsWith("/covers/")) return pathname;

  if (isEphemeralPath(pathname) && process.env.USE_UPLOAD_IMAGES === "1") {
    return pathname;
  }

  return fallback;
}

/** Absolute URL for OG / JSON-LD. */
export function absoluteCover(
  featuredImage: string | null | undefined,
  categorySlug: string | null | undefined,
  siteUrl: string,
  postSlug?: string | null
): string {
  const src = resolveCover(featuredImage, categorySlug, postSlug);
  return src.startsWith("http") ? src : `${siteUrl.replace(/\/$/, "")}${src}`;
}

/**
 * Social previews (Facebook, X, LinkedIn, WhatsApp) do not render SVG og:images.
 * Every /covers/<name>.svg has a 1200x630 PNG twin at /covers/og/<name>.png, and every
 * /covers/posts/<slug>.webp has a PNG twin at /covers/posts/<slug>.png.
 */
export function ogCover(
  featuredImage: string | null | undefined,
  categorySlug: string | null | undefined,
  siteUrl: string,
  postSlug?: string | null
): string {
  const src = resolveCover(featuredImage, categorySlug, postSlug);
  const own = src.match(/^\/covers\/posts\/([a-z0-9-]+)\.webp$/i);
  const m = src.match(/^\/covers\/([a-z0-9-]+)\.svg$/i);
  const path = own ? `/covers/posts/${own[1]}.png` : m ? `/covers/og/${m[1]}.png` : src;
  return path.startsWith("http") ? path : `${siteUrl.replace(/\/$/, "")}${path}`;
}

export const DEFAULT_OG_IMAGE = "/covers/og/default.png";
